version: '3'
services:
  mysql_db:
    image: mysql # pull image có tên là mysql trên docker hub về local
    container_name: mysql_db # trở thành host
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3308:3306
    networks:
      - node38-networks
  node38:
    depends_on:
      - mysql_db
    build: . # tìm Dockerfile trong source BE để build image BE
    container_name: node38_nest
    env_file:
      - .env
    ports:
      - 3000:3001
    networks:
      - node38-networks
networks:
  node38-networks:
